### ISSUE TITLE
Address bar icon has poor contrast in dark mode

### ISSUE THREAD

**Issue by bbhtt** [Johennes/wallabaggerini#3]
Maybe it'd be better to switch it to a white icon in dark mode

![image](https://user-images.githubusercontent.com/62639087/184084598-3be3dff3-0ee6-44d8-9a70-c44984e91e6d.png)

**Comment by Johennes** [comment]
Thanks for filing this. I found a way to toggle the icon that works as long as you don't chose the system theme. That and the fix for #2 will be included in version 0.2.0 which I just uploaded to addons.mozilla.org.

**Comment by bbhtt** [comment]
The icon seems to reset back to the dark one every once in a while. I can initially see the white icon when I switch the theme from System to Dark, but if I open a page, it seems to reset back to the dark icon.


https://user-images.githubusercontent.com/62639087/185530481-f0084cf6-b8c6-4978-bfdf-3b1d9422bc6c.mp4

**Comment by Johennes** [comment]
Hm, this was trickier to fix than expected. Apparently the page action icon can only be set when the page action is currently shown. There is no event for when the page action is shown / hidden though so I had to hook into general tab updates. Just uploaded 0.2.1 which should fix this reasonably well.

**Comment by bbhtt** [comment]
> Just uploaded 0.2.1 which should fix this reasonably well.

Thanks! Seems to work now.
